- name: "{{ http_pkg }} package deployment"
  package:
    name: "{{ http_pkg }}"
    state: latest

- name: install haproxy  
  yum:
    name: "{{ haproxy_pkg }}"
    state: latest

- name: enable haproxy 
  service:
    name: "{{ haproxy_service }}"
    state: started
    enabled: yes

- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
 
  notify:
    - restart HAproxy 
